site_name: RenderCV App
site_url: https://rendercv.com
site_description: An open-source LaTeX CV/resume generator
docs_dir: src
copyright: Copyright &copy; 2024 Sina Atalay and Meriç Üngör
repo_url: https://github.com/sinaatalay/rendercv
repo_name: sinaatalay/rendercv

theme:
  name: material
  language: en
  locale: en
  custom_dir: src/assets/overrides
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"
  features:
    - content.code.copy # the copy-to-clipboard buttons for code blocks
    - navigation.indexes # allow mother pages to have their own index pages
    - navigation.instant # instant navigation for faster page loads
    - navigation.instant.prefetch # prefetch pages for instant navigation
    - navigation.instant.progress # show progress bar for instant navigation
    - navigation.top # back to top button
    - search.highlight # highlight search results after going to a page
    - search.suggest # show search suggestions while typing
    - search.share # share search results with others
    - toc.follow # if toc sidebar doesn't fit, scroll to the active heading
    - content.code.annotate # allow annotations in code blocks

font:
  text: Roboto
  code: Roboto Mono

nav:
  - Home: index.md
  - Blog: blog/index.md

plugins:
  - macros: # https://github.com/fralau/mkdocs-macros-plugin
      module_name: src/assets/data/data

  - blog:
      blog_dir: blog
      post_dir: "{blog}/posts"
      authors_file: "{blog}/authors.yaml"
      post_url_format: "blog/{slug}"
      archive: false

markdown_extensions:
  - attr_list # allow assigning HTML attributes to elements
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.pathconverter # convert relative paths to absolute paths
  - pymdownx.betterem
  - pymdownx.tabbed: # content tabs
      alternate_style: true

extra_javascript:
  - https://cdn.tailwindcss.com
  - assets/javascripts/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/contrib/auto-render.min.js

extra_css:
  - assets/stylesheets/rendercv.css
  - assets/stylesheets/tailwind.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css


extra:
  #  analytics:
  #    provider: google
  #    property: G-HH8XZL6SQK
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sinaatalay/rendercv

  status:
    new: "New"
